### PR TITLE
Remove unconsidered security template

### PR DESCRIPTION
**Pull request by NotMyFault**
Hey,

I see you have specified a custom security contact in the SECURITY.md. However, this file is not considered for custom data.

If you want to have a public security contact, please [see the documentation](https://github.com/jenkins-infra/repository-permissions-updater#managing-security-process) how to add it to your [repository file](https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-anka-build.yml).

Only contacts specified here will be considered.

Thanks!

### CODE REVIEW

**Comment by NorseGaud** [comment]
@NotMyFault, can we have both? Why would we remove a perfectly good file that many people look for?

**Comment by NotMyFault** [comment]
You surely can have a custom file, but I recommend updating it to comply with our standards of vulnerability disclosure: https://www.jenkins.io/security/reporting/

A security contact specified will be contacted if someone reports a vulnerability through the standard procedure.

**Comment by NivKeidan** [comment]
hey @NotMyFault , thanks for bringing our attention to this.

We would definitely like to add a point of contact, but it will be one of our current maintainers, and as the docs state:

> ...specifying a Jira security contact is only useful when it's an account not already listed as maintainer.

Should we still add a point of contact just to resolve the issue you mention?

Much obliged :pray:

**Comment by NotMyFault** [comment]
If I remember correctly, we used to specify both, historically.

**Comment by NivKeidan** [comment]
https://github.com/jenkins-infra/repository-permissions-updater/pull/3039

**Pull request closed without merging**
