### PR TITLE
Feature: Optional tag timestamp

### PR DESCRIPTION
**Pull request by thecodesmith**
Greetings! 

At Jamf we use a tag strategy that does not include timestamps. This PR makes the appending of a timestamp optional. If not specified, it defaults to `true` to maintain backwards compatible behavior. This feature was created off the `release/v1.24.0` branch, since we are still using the 1.x version of the plugin. I did not see a 1.x maintenance branch to target this to, is there one?

Please let me know if you see any issues here, any feedback is welcome.

Thanks!
Brian

### CODE REVIEW

**Comment by NorseGaud** [comment]
@NivKeidan @asafg6

**Comment by NorseGaud** [comment]
Hey @thecodesmith, thank you so much for the contribution! We'll have our devs look at this right away. However, I will mention that versions < 2.X are EOL in roughly a month from now. I'm certain this code can be retrofitted, but I'll let our devs follow up with you about it. 

Thanks again!

**Comment by thecodesmith** [comment]
@NorseGaud, that makes sense regarding the 1.x EOL. I'd be happy to open a PR for this same change to the 2.x line once we are able to upgrade. We are stuck on 1.x for now due to a performance issue that we are currently investigating.

**Comment by asafg6** [comment]
@thecodesmith this is great! :+1: 
Unfortunately I can't merge it to master.
Some of the changes in this branch will undo a lot of hard work we did on 2.x.x .
About release/v1.24.0 - it was never released, nor tested. So, use at your own risk.
I will happily merge your pr to release/v1.24.0

**Comment by NorseGaud** [comment]
Hey @thecodesmith, I'll have TJ within your org reach out to you as he's the most familiar with the current status of upgrading to 2.X. To summarize what's blocking your upgrade: there seems to be something in your environment that is dropping the connectivity of Jenkins JNLP to the Anka VMs inconsistently and rarely. The current version you're on (1.22.4) has a successor (1.23) which could be upgraded to, but it also is going to be EOL soon. You're more than welcome to fork and work off of 1.23, but that limits the support we can provide and I highly recommend against it.

**Comment by thecodesmith** [comment]
@NorseGaud @asafg6, thanks for the feedback! After discussing with TJ, what we'd like to do is redo this PR targeting `master`, and we will just have to wait on using it ourselves for when we are able to upgrade to 2.x. Thanks for taking a look! I'll close this out for now, and reopen when we have the new implementation.

**Pull request closed without merging**
