### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by darxriggs**
I suggest to review this pull request commit by commit as each one addresses a different aspect.

### CODE REVIEW

**Comment by darxriggs** [comment]
Hi @asaf, as some time already passed since this pull-request was created, I just wanted to check if it can be merged?

**Comment by darxriggs** [comment]
Yes, `httpClient.close()` will automatically be called. That's exactly what the try-with-resources construct is for. For some details and examples see https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html.

**Comment by darxriggs** [comment]
Hi, I just resolved the merge conflict by merging master into this pull request.
As it was already approved, I wanted to ask if it can also be merged?

**Comment by darxriggs** [comment]
@alexf123 ping

**Comment by darxriggs** [comment]
@alexf123 / @alexfs is there a chance to get this merged?

**Comment by asafg6** [comment]
Sorry, these changes will not be merged since they do not offer any new functionality.

**Pull request closed without merging**
